# Generated by Django 6.0.5 on 2026-05-11 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNumber', models.IntegerField()),
                ('roomType', models.CharField(max_length=16)),
                ('price', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkInDate', models.DateField(null=True)),
                ('checkOutDate', models.DateField(null=True)),
                ('totalPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.room')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paymentDate', models.DateField(null=True)),
                ('paymentMethod', models.CharField(max_length=12)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.reservation')),
            ],
        ),
    ]
